# Generated by Django 5.0.6 on 2024-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tproduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomp', models.CharField(max_length=50, unique=True, verbose_name='Nom produit')),
                ('stock', models.IntegerField(default=1)),
                ('prix', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produit/')),
            ],
        ),
    ]
