# Generated by Django 5.0.6 on 2024-06-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwetuProduction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tentreprsie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomE', models.CharField(max_length=50, unique=True, verbose_name='Nom entreprise')),
                ('emailE', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='tproduit',
            name='idEntrep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='KwetuProduction.tentreprsie'),
        ),
    ]
