# Generated by Django 5.0.6 on 2024-06-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwetuProduction', '0003_tcathegorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tproduit',
            name='idCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KwetuProduction.tcathegorie'),
        ),
        migrations.AlterField(
            model_name='tproduit',
            name='idEntrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='KwetuProduction.tentreprsie'),
        ),
    ]
