# Generated by Django 5.0.6 on 2024-06-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KwetuProduction', '0005_tentreprsie_deescriptione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentreprsie',
            old_name='deescriptionE',
            new_name='descriptionE',
        ),
    ]
