# Generated by Django 5.0.6 on 2024-06-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imgProfil',
            field=models.ImageField(blank=True, null=True, upload_to='imgProfil/', verbose_name='Photo de profil'),
        ),
    ]
